### ISSUE TITLE
Are semicolons really needed?

### ISSUE THREAD

**Issue by Aidan-The-Dev** [TriSn0w/EnScript#2]
Just as a test I removed the check for the semicolon and it still works perfectly fine is the semicolon requirement just to make it unique?

**Comment by itisdoc** [comment]
Kind of, yes. It was added before so it would be easier to check when a line ended, but now its not needed

**Comment by AidanTheJsDev** [comment]
You can close this

Edit: Sent from my school account im Aidan-The-Dev
